#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
clear
MYIP=$(wget -qO- ipinfo.io/ip);
clear
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
BGWHITE='\e[0;47;30m'
BGBLUE='\e[1;44m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'
BLACK='\033[0;30m'
GRBK='\033[0;40m'
BOLD='\e[1m'
END='\e[0m'

add-ip() {
    today=`date -d "0 days" +"%Y-%m-%d"`
    ran=$(date +%s)
    git clone https://github.com/OrderMyAutoScript/kintil.git /root/ipvps/ &> /dev/null
    clear
    read -p "Input IP Address : " ip
    CLIENT_EXISTS=$(grep -w $ip /root/ipvps/ip | wc -l)
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo "IP Already Exist !"
    exit 0
    fi
    read -p "Input Username IP (Example : bahenol) : " name
    read -p "Input Code Unik : " unix
    export unix=""$(</dev/urandom tr -dc 0-9 | head -c3)
    echo "How Much Days Do You Want ?"
    echo -e "${GREEN}[${Lyellow}1${GREEN}]\033[0;36m 30 Days $NC"
    echo -e "${GREEN}[${Lyellow}2${GREEN}]\033[0;36m 60 Days $NC"
    echo -e "${GREEN}[${Lyellow}3${GREEN}]\033[0;36m 90 Days $NC"
    echo -e "${GREEN}[${Lyellow}4${GREEN}]\033[0;36m Lifetime $NC"
    echo -e "${GREEN}[${Lyellow}5${GREEN}]\033[0;36m Set Custom Expiration Date $NC"
    read -p "Input Menu Number : " exp
    
    if [[ ${exp} == '1' ]]; then
    exp2=`date -d "30 days" +"%Y-%m-%d"`
    echo "### ${name}${unix} $ran ${exp2} ${ip} V3.0" >> /root/ipvps/ip
    elif [[ ${exp} == '2' ]]; then
    exp2=`date -d "60 days" +"%Y-%m-%d"`
    echo "### ${name}${unix} $ran ${exp2} ${ip} V3.0" >> /root/ipvps/ip
    elif [[ ${exp} == '3' ]]; then
    exp2=`date -d "90 days" +"%Y-%m-%d"`
    echo "### ${name}${unix} $ran ${exp2} ${ip} V3.0" >> /root/ipvps/ip
    elif [[ ${exp} == '4' ]]; then
    exp2="Lifetime"
    echo "### ${name}${unix} $ran ${exp2} ${ip} V3.0" >> /root/ipvps/ip
    elif [[ ${exp} == '5' ]]; then
    read -p "Input Expired Days : " exp11
    exp2=`date -d "$exp11 days" +"%Y-%m-%d"`
    echo "### ${name}${unix} $ran ${exp2} ${ip} V3.0" >> /root/ipvps/ip
    fi
    cd /root/ipvps
    git config --global user.email "ordermyautoscript@hotmail.com" &> /dev/null
    git config --global user.name "OrderMyAutoScript" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m REGISTER-IP &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/OrderMyAutoScript/kintil
    git push -f https://ghp_pMYvgV7kzc9F1V5DSLMmrBMJOCe1gpTJM@github.com/OrderMyAutoScript/kintil.git &> /dev/null
    rm -rf /root/ipvps
    clear
    echo -e "${CYAN}Succesfully Add IP Address${NC}"
    echo -e ""
    echo -e "Username      : $name$unix"
    echo -e "IP Address    : $ip"
    echo -e "Order ID      : $ran"
    echo -e "Registered On : $today"
    echo -e "Expired On    : $exp2"
    echo ""
}

del-ip() {
    rm -rf /root/ipvps
    git clone https://github.com/OrderMyAutoScript/kintil.git /root/ipvps/ &> /dev/null
    clear
    echo "List IP Address Have Been Registered"
    echo ""
    grep -E "^###" "/root/ipvps/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    grep -E "^#&" "/root/ipvps/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo ""
    read -p "Input IP Address To Delete : " ipdel
    name=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $2}')
    oid=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $3}')
    exp=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $4}')
    if [[ ${exp} == 'Lifetime' ]]; then
    sed -i "/^#& $name $oid $exp $ipdel/,/^},{/d" /root/ipvps/ip
    else
    sed -i "/^### $name $oid $exp $ipdel/,/^},{/d" /root/ipvps/ip
    fi
    cd /root/ipvps
    git config --global user.email "ordermyautoscript@hotmail.com" &> /dev/null
    git config --global user.name "OrderMyAutoScript" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m REGISTER-IP &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/OrderMyAutoScript/kintil
    git push -f https://ghp_vG0OtdVMU0vIB85teJ95Ee3qj47Wn1Y@github.com/OrderMyAutoScript/kintil.git &> /dev/null
    rm -rf /root/ipvps
    clear
    echo "Succesfully Deleted The IP Address"
    
}

renew-ip() {
    rm -rf /root/ipvps
    git clone https://github.com/OrderMyAutoScript/kintil.git /root/ipvps/ &> /dev/null
    clear
    echo "List IP Address Have Been Registered"
    echo ""
    grep -E "^###" "/root/ipvps/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo ""
    read -p "Input IP Address To Renew : " ipdel
    read -p "Input Days  : " days
    name=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $2}')
    oid=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $3}')
    exp=$(cat /root/ipvps/ip | grep $ipdel | awk '{print $4}')
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $days))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/### $name $oid $exp $ipdel/### $name $oid $exp4 $ipdel/g" /root/ipvps/ip
    cd /root/ipvps
    git config --global user.email "ordermyautoscript@hotmail.com" &> /dev/null
    git config --global user.name "OrderMyAutoScript" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m REGISTER-IP &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/OrderMyAutoScript/kintil
    git push -f https://ghp_vG0OtdVMU0vIB85teJ95Ee3qj47Wn1Y@github.com/OrderMyAutoScript/kintil.git &> /dev/null
    rm -rf /root/ipvps
    clear
    echo "Succesfully Renew The IP Address"
    echo ""
    echo "Username   : $name"
    echo "IP Address : $ipdel"
    echo "Order ID   : $oid"
    echo "Expired On : $exp4"
    echo ""
}

clear

echo -e "${Lred} ════════════════════════════════════════${NC}"
echo -e " ${BGWHITE}        [ REGISTER IP MENU ]            ${NC}"
echo -e "${Lred} ════════════════════════════════════════${NC}"
echo -e " $PURPLE (01) $NC $Lyellow Add IP VPS"$NC     
echo -e " $PURPLE (02) $NC $Lyellow Renew IP VPS"$NC
echo -e " $PURPLE (00) $NC $Lyellow Back to Menu"$NC
echo -e "${Lred} ════════════════════════════════════════${NC}"
echo ""
read -p "Please Input Menu Number : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
renew-ip
;;
0 | 00)
clear
menu
;;
*)
echo -e ""
add
;;
esac
